### Step1: import numpy

In [1]:
import numpy as np

### 2. Arry in numpy

In [9]:
## 2.1 Scalar array
a= np.array(10)
print(a)

## 2.2 Vactor array
b= np.array([1,2,3])
print(b)

## 2.3 Matrix array
c= np.array([[1], [2], [3]]) # 3 row and 1 column
d= np.array([[1,2], [2,3], [3,4]]) # 3 rows and 2 column
matrix= np.array([[10,11,12], [13,14,15]]) ## 2rows and 3 column 2*3
print(c)
print(matrix)

10
[1 2 3]
[[1]
 [2]
 [3]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


### 3. finding statistic value by numpy

In [14]:
stat = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]]) # 3x4 matrix
print(stat)

## find max and min value

print('Max:', np.max(stat))
print('Min:', np.min(stat))
print('Mean:', np.mean(stat))
print('median:', np.median(stat))
print('Standard deviation:', np.std(stat)) #  ຄ່າບ່ຽງເບນ
print('Varience:', np.var(stat)) # ຄ່າແປປວນ

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max: 12
Min: 1
Mean: 6.5
median: 6.5
Standard deviation: 3.452052529534663
Varience: 11.916666666666666
